; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps =
	bblanchon/ArduinoJson@^7.2.2
	;paulstoffregen/AltSoftSerial@^1.4 //required for LSSCommsTest.cpp - using SoftSerial once LSS was functioning
	;khoih-prog/AVR_Slow_PWM@^1.2.3 // required for FixedWingV2_DSEI.cpp - moved to using regular Uno Timers for PWM
